USE [master]
GO
CREATE DATABASE [EnglishVocabularyQuiz]
GO
USE [EnglishVocabularyQuiz]
GO
CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    UserName NVARCHAR(255) UNIQUE NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    FullName NVARCHAR(100),
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Vocabulary (
    WordID INT PRIMARY KEY IDENTITY(1,1),
    EnglishWord NVARCHAR(255) NOT NULL,
    VietnameseWord NVARCHAR(255) NOT NULL,
    WordType NVARCHAR(50), -- Loại từ: Noun, Verb, Adjective, v.v.
    CreatedAt DATETIME DEFAULT GETDATE()
);

INSERT INTO Users (UserName, Password, FullName)
VALUES 
(N'usertam', N'123', N'Nguyen Xuan Tam'),
(N'user1', N'123', N'Nguyen Van A'),
(N'user2', N'123', N'Tran Thi B'),
(N'user3', N'123', N'Le Van C');

INSERT INTO Vocabulary (EnglishWord, VietnameseWord, WordType)
VALUES 
(N'Apple', N'Táo', N'Noun'),
(N'Run', N'Chạy', N'Verb'),
(N'Beautiful', N'Đẹp', N'Adjective'),
(N'Dog', N'Chó', N'Noun'),
(N'Eat', N'Ăn', N'Verb'),
(N'Smart', N'Thông minh', N'Adjective'),
(N'Cat', N'Mèo', N'Noun'),
(N'Write', N'Viết', N'Verb'),
(N'Happy', N'Vui vẻ', N'Adjective'),
(N'Book', N'Sách', N'Noun'),
(N'Orange', N'Cam', N'Noun'),
(N'Jump', N'Nhảy', N'Verb'),
(N'Clever', N'Thông minh', N'Adjective'),
(N'House', N'Nhà', N'Noun'),
(N'Sleep', N'Ngủ', N'Verb'),
(N'Bright', N'Sáng', N'Adjective'),
(N'Bird', N'Chim', N'Noun'),
(N'Dance', N'Nhảy múa', N'Verb'),
(N'Wonderful', N'Tuyệt vời', N'Adjective'),
(N'Chair', N'Ghế', N'Noun'),
(N'Run', N'Chạy', N'Verb'),
(N'Delicious', N'Ngon', N'Adjective'),
(N'Car', N'Xe hơi', N'Noun'),
(N'Sing', N'Hát', N'Verb'),
(N'Friendly', N'Thân thiện', N'Adjective'),
(N'Computer', N'Máy tính', N'Noun'),
(N'Read', N'Đọc', N'Verb'),
(N'Angry', N'Giận dữ', N'Adjective'),
(N'Tree', N'Cây', N'Noun'),
(N'Swim', N'Bơi', N'Verb'),
(N'Funny', N'Hài hước', N'Adjective'),
(N'Phone', N'Diện thoại', N'Noun'),
(N'Talk', N'Nói', N'Verb'),
(N'Pretty', N'Xinh đẹp', N'Adjective'),
(N'Window', N'Cửa sổ', N'Noun'),
(N'Fly', N'Bay', N'Verb'),
(N'Tall', N'Cao', N'Adjective'),
(N'Laptop', N'Máy tính xách tay', N'Noun'),
(N'Write', N'Viết', N'Verb'),
(N'Brave', N'Dũng cảm', N'Adjective'),
(N'Fish', N'Cá', N'Noun'),
(N'Help', N'Giúp đỡ', N'Verb'),
(N'Kind', N'Tốt bụng', N'Adjective'),
(N'Bread', N'Bánh mì', N'Noun'),
(N'Cook', N'Nấu ăn', N'Verb'),
(N'Lucky', N'May mắn', N'Adjective'),
(N'Pencil', N'Bút chì', N'Noun'),
(N'Draw', N'Vẽ', N'Verb'),
(N'Careful', N'Cẩn thận', N'Adjective'),
(N'Sun', N'Mặt trời', N'Noun'),
(N'Build', N'Xây dựng', N'Verb'),
(N'Cheerful', N'Vui tươi', N'Adjective'),
(N'Fish', N'Cá', N'Noun'),
(N'Listen', N'Nghe', N'Verb'),
(N'Confident', N'Tự tin', N'Adjective'),
(N'Grass', N'Cỏ', N'Noun'),
(N'Clean', N'Dọn dẹp', N'Verb'),
(N'Curious', N'Tò mò', N'Adjective'),
(N'Tea', N'Trà', N'Noun'),
(N'Hug', N'Ôm', N'Verb'),
(N'Sincere', N'Chân thành', N'Adjective'),
(N'Mountain', N'Núi', N'Noun'),
(N'Catch', N'Bắt', N'Verb'),
(N'Courageous', N'Can đảm', N'Adjective'),
(N'Fruit', N'Trái cây', N'Noun'),
(N'Dance', N'Nhảy múa', N'Verb'),
(N'Funny', N'Hài hước', N'Adjective'),
(N'Vegetable', N'Rau củ', N'Noun'),
(N'Jump', N'Nhảy', N'Verb'),
(N'Happy', N'Hạnh phúc', N'Adjective'),
(N'Chair', N'Ghế', N'Noun'),
(N'Swim', N'Bơi', N'Verb'),
(N'Quick', N'Nhanh', N'Adjective'),
(N'Shirt', N'Áo sơ mi', N'Noun'),
(N'Read', N'Đọc', N'Verb'),
(N'Slow', N'Chậm', N'Adjective'),
(N'Game', N'Trò chơi', N'Noun'),
(N'Cook', N'Nấu ăn', N'Verb'),
(N'Calm', N'Bình tĩnh', N'Adjective'),
(N'Market', N'Chợ', N'Noun'),
(N'Drive', N'Lái xe', N'Verb'),
(N'Strong', N'Mạnh mẽ', N'Adjective'),
(N'City', N'Thành phố', N'Noun'),
(N'Play', N'Chơi', N'Verb'),
(N'Sweet', N'Ngọt ngào', N'Adjective'),
(N'House', N'Nhà', N'Noun'),
(N'Write', N'Viết', N'Verb'),
(N'Bright', N'Sáng', N'Adjective'),
(N'School', N'Trường học', N'Noun'),
(N'Sing', N'Hát', N'Verb'),
(N'Dark', N'Tối', N'Adjective'),
(N'Store', N'Cửa hàng', N'Noun'),
(N'Paint', N'Vẽ', N'Verb'),
(N'Rich', N'Giàu có', N'Adjective'),
(N'Animal', N'Động vật', N'Noun'),
(N'Run', N'Chạy', N'Verb'),
(N'Kind', N'Tốt bụng', N'Adjective'),
(N'Family', N'Gia đình', N'Noun'),
(N'Talk', N'Nói chuyện', N'Verb'),
(N'Friendly', N'Thân thiện', N'Adjective'),
(N'Library', N'Thư viện', N'Noun'),
(N'Throw', N'Ném', N'Verb'),
(N'Interesting', N'Thú vị', N'Adjective'),
(N'Park', N'Công viên', N'Noun'),
(N'Catch', N'Bắt', N'Verb'),
(N'Proud', N'Tự hào', N'Adjective'),
(N'Journey', N'Hành trình', N'Noun'),
(N'Win', N'Thắng', N'Verb'),
(N'Unique', N'Độc đáo', N'Adjective'),
(N'Story', N'Câu chuyện', N'Noun'),
(N'Sleep', N'Ngủ', N'Verb'),
(N'Mysterious', N'Huyền bí', N'Adjective'),
(N'Game', N'Trò chơi', N'Noun'),
(N'Teach', N'Dạy', N'Verb'),
(N'Wonderful', N'Kỳ diệu', N'Adjective'),
(N'Festival', N'Lễ hội', N'Noun'),
(N'Chase', N'Theo đuổi', N'Verb'),
(N'Generous', N'Hào phóng', N'Adjective'),
(N'Dream', N'Giấc mơ', N'Noun'),
(N'Explore', N'Khám phá', N'Verb'),
(N'Peaceful', N'Yên bình', N'Adjective'),
(N'Mountain', N'Núi', N'Noun'),
(N'Climb', N'Leo núi', N'Verb');
